# Generated by Django 4.2.20 on 2025-03-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='experience',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='status',
        ),
    ]
