# Generated by Django 4.2.20 on 2025-03-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_remove_class_start_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50),
        ),
    ]
